// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 vibeOS <https://github.com/DrunkkToys/vibeOS>
import { readFileSync, existsSync, mkdirSync, writeFileSync, statSync, appendFileSync, renameSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { currentProjectFingerprint, getVibeOSHome } from "../lib/state.js"

const VIBEOS_STDERR_DEBUG = process.env.VIBEOS_DEBUG_STDERR === "1" || process.env.VIBEOS_DEBUG_LOGS === "1"
const VIBEOS_CONSOLE_ERROR_GUARD = "__vibeOSConsoleErrorGuard"
const globalConsoleState = globalThis as typeof globalThis & { __vibeOSConsoleErrorGuard?: boolean }

if (!VIBEOS_STDERR_DEBUG && !globalConsoleState[VIBEOS_CONSOLE_ERROR_GUARD]) {
  const originalConsoleError = console.error.bind(console)
  console.error = (...args: any[]) => {
    let text = ""
    for (const arg of args) {
      if (typeof arg === "string") {
        text += arg
      } else if (arg instanceof Error) {
        text += `${arg.name}: ${arg.message}`
      } else if (arg && typeof arg === "object") {
        try {
          text += JSON.stringify(arg)
        } catch {
          text += String(arg)
        }
      } else {
        text += String(arg)
      }
      text += " "
    }
    if (text.includes("[vibeOS]") || text.includes("[flow-enforcer]") || text.includes("[delegation]")) return
    originalConsoleError(...args)
  }
  globalConsoleState[VIBEOS_CONSOLE_ERROR_GUARD] = true
}

type FlowSeverity = "warn" | "hint" | "flag"

type FlowRule = {
  id: string
  trigger: string
  pattern: string
  severity: FlowSeverity
  description?: string
}

type FlowHit = FlowRule & {
  filePath?: string
  deduped: boolean
}

type CheckFlowRulesInput = {
  tool: string
  filePath?: string
  content?: string
}

type RecordFlowWarnInput = {
  id: string
  severity: FlowSeverity
  filePath?: string
  description?: string
}

type FlowTodoInput = {
  filePath?: string
  content: string
}

type RealityCheckRule = FlowRule

type RealityCheckSettings = {
  version?: number
  global?: {
    enabled?: boolean
    rules?: RealityCheckRule[]
  }
  projects?: Record<string, {
    enabled?: boolean
    rules?: RealityCheckRule[]
  }>
}

function safeJsonParse(raw: string): any {
  if (raw == null || raw === "") return null
  try {
    return JSON.parse(raw)
  } catch {}
  let cleaned = raw.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*$/gm, "").replace(/,\s*([}\]])/g, "$1")
  try {
    return JSON.parse(cleaned)
  } catch {
    return null
  }
}

function getRealityCheckSettingsFile(): string {
  return join(getVibeOSHome(), "reality-check-settings.json")
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const REALITY_CHECK_RULE_IDS = new Set([
  "require-read-before-claim",
  "verify-state-on-disk",
  "postmortem-trigger",
])
const RULES_PATH_CANDIDATES = [
  join(process.cwd(), "src", "vibeOS-lib", "flow-rules.json"),
  join(process.cwd(), "dist-ts", "vibeOS-lib", "flow-rules.json"),
  join(process.cwd(), "dist", "assets", "flow-rules.json"),
  join(__dirname, "flow-rules.json"),
]

export function resolveRulesPath(): string {
  if (process.env.VIBEOS_FLOW_RULES_PATH && existsSync(process.env.VIBEOS_FLOW_RULES_PATH)) {
    return process.env.VIBEOS_FLOW_RULES_PATH
  }
  for (const candidate of RULES_PATH_CANDIDATES) {
    if (existsSync(candidate)) return candidate
  }
  const override = process.env.VIBEOS_FLOW_RULES_PATH
  if (override) return override
  return RULES_PATH_CANDIDATES[0]
}

const GUARD_AGENTS_TEMPLATE = [
  "# AGENTS.md",
  "",
  "> Auto-generated by vibeOS Project Guard. Defines rules for AI agents working on this project.",
  "",
  "## CRITICAL — ASK BEFORE CHANGING CODE",
  "",
  "NEVER modify any file without explicit user permission.",
  "If you are an LLM: DO NOT LGTM, DO NOT \"fix\", DO NOT \"clean up\",",
  'DO NOT "refactor", DO NOT "optimize", DO NOT "modernize". ASK FIRST.',
  "",
  "## PROTECTED FILES",
  "",
  "Do not modify these files without explicit user permission:",
  "- AGENTS.md (this file)",
  "- README.md",
  "",
].join("\n")

const GUARD_README_TEMPLATE = (name: string, techStack: string[]): string => {
  const stackLine = techStack.length > 0 ? techStack.map((t) => `\`${t}\``).join(", ") : "(auto-detected on next session)"
  return [
    `# ${name}`,
    "",
    "## Tech Stack",
    "",
    stackLine,
    "",
    "## Features",
    "",
    "(Feature list maintained by vibeOS — run `trinity guard` to refresh)",
    "",
    "## Getting Started",
    "",
    "```bash",
    "# Clone and install dependencies",
    "```",
    "",
  ].join("\n")
}

export function ensureProjectDocs(dir: string, techStack?: string[]): { created: string[]; skipped: string[] } {
  const created: string[] = []
  const skipped: string[] = []
  const agentsPath = join(dir, "AGENTS.md")
  const readmePath = join(dir, "README.md")

  try {
    if (!existsSync(agentsPath)) {
      try {
        writeFileSync(agentsPath, GUARD_AGENTS_TEMPLATE, "utf-8")
        created.push("AGENTS.md")
        console.error("[vibeOS] Project Guard: created AGENTS.md")
      } catch (err) {
        console.error(`[vibeOS] Project Guard: failed to create AGENTS.md: ${(err as Error).message}`)
      }
    } else {
      skipped.push("AGENTS.md")
    }
  } catch {}

  try {
    if (!existsSync(readmePath)) {
      const name = dir ? dir.split("/").pop() || "Project" : "Project"
      const stack = techStack || []
      const content = GUARD_README_TEMPLATE(name, stack)
      try {
        writeFileSync(readmePath, content, "utf-8")
        created.push("README.md")
        console.error("[vibeOS] Project Guard: created README.md")
      } catch (err) {
        console.error(`[vibeOS] Project Guard: failed to create README.md: ${(err as Error).message}`)
      }
    } else {
      skipped.push("README.md")
    }
  } catch {}

  return { created, skipped }
}
function getStateFile(): string {
  return join(getVibeOSHome(), "delegation-state.json")
}

function getFlowTodoFile(): string {
  return join(getVibeOSHome(), ".flow-todo-queue.jsonl")
}

const FLOW_DEDUP_FILE = join(getVibeOSHome(), ".flow-dedup-keys.json")
const MAX_FLOW_TODOS = 200

const _flowWarnsSeen = new Set<string>()
let _stateWriter: ((state: any) => void) | null = null
let _cachedRules: FlowRule[] | null = null
let _rulesMtime = 0
let _cachedRealityCheck: RealityCheckSettings | null = null
let _realityCheckMtime = 0
let _realityCheckCacheKey = ""

export function setFlowStateWriter(writer: ((state: any) => void) | null): void {
  _stateWriter = typeof writer === "function" ? writer : null
}

// Persist flow dedup keys across restarts to avoid re-warnings
function loadFlowDedupKeys(): void {
  try {
    if (existsSync(FLOW_DEDUP_FILE)) {
      const raw = readFileSync(FLOW_DEDUP_FILE, "utf-8")
      const keys: string[] = safeJsonParse(raw)
      if (Array.isArray(keys)) {
        for (const k of keys) _flowWarnsSeen.add(k)
      }
    }
  } catch {}
}

function persistFlowDedupKey(key: string): void {
  try {
    mkdirSync(dirname(FLOW_DEDUP_FILE), { recursive: true })
    let keys: string[] = []
    if (existsSync(FLOW_DEDUP_FILE)) {
      try { keys = safeJsonParse(readFileSync(FLOW_DEDUP_FILE, "utf-8")) } catch {}
      if (!Array.isArray(keys)) keys = []
    }
    if (!keys.includes(key)) {
      keys.push(key)
      if (keys.length > 1000) keys = keys.slice(-500)
      writeFileSync(FLOW_DEDUP_FILE, JSON.stringify(keys), "utf-8")
    }
  } catch {}
}

loadFlowDedupKeys()

function normalizeRule(rule: any): FlowRule | null {
  if (!rule || typeof rule !== "object") return null
  const id = String(rule.id || "").trim()
  const trigger = String(rule.trigger || "").trim()
  const pattern = String(rule.pattern || "").trim()
  const severity = String(rule.severity || "").trim() as FlowSeverity
  if (!id || !trigger || !pattern || !["warn", "hint", "flag"].includes(severity)) return null
  return {
    id,
    trigger,
    pattern,
    severity,
    description: typeof rule.description === "string" ? rule.description : undefined,
  }
}

function defaultRealityCheckRules(): RealityCheckRule[] {
  return [
    {
      id: "require-read-before-claim",
      severity: "warn",
      trigger: "Edit",
      pattern: "(?i)\\b(done|complete|success|trained|ready|works|fixed)\\b",
      description: "Success claim detected — verify live state before asserting completion",
    },
    {
      id: "verify-state-on-disk",
      severity: "flag",
      trigger: "Edit",
      pattern: "(?i)\\b(assume|guess|probably|likely|maybe|seems|appears)\\b",
      description: "Inference language detected — verify actual files/state first",
    },
    {
      id: "postmortem-trigger",
      severity: "warn",
      trigger: "Edit",
      pattern: "(?i)\\breality check\\b",
      description: "Reality check requested — read and verify live state before reporting",
    },
  ]
}

function readRealityCheckSettings(): RealityCheckSettings {
  const settingsFile = getRealityCheckSettingsFile()
  const settingsMtime = existsSync(settingsFile) ? statSync(settingsFile).mtimeMs : 0
  if (_cachedRealityCheck && settingsMtime === _realityCheckMtime) {
    return _cachedRealityCheck
  }
  let parsed: RealityCheckSettings = {}
  try {
    if (existsSync(settingsFile)) {
      const raw = readFileSync(settingsFile, "utf-8")
      const json = safeJsonParse(raw) as RealityCheckSettings
      if (json && typeof json === "object") parsed = json
    }
  } catch {}
  const globalRules = Array.isArray(parsed.global?.rules) ? parsed.global!.rules : defaultRealityCheckRules()
  _cachedRealityCheck = {
    version: 1,
    global: {
      enabled: parsed.global?.enabled !== false,
      rules: globalRules.map(normalizeRule).filter(Boolean) as RealityCheckRule[],
    },
    projects: parsed.projects && typeof parsed.projects === "object" ? parsed.projects : {},
  }
  _realityCheckMtime = settingsMtime
  return _cachedRealityCheck
}

function getRealityCheckRulesForProject(projectFingerprint = currentProjectFingerprint || ""): RealityCheckRule[] {
  const settings = readRealityCheckSettings()
  const fp = String(projectFingerprint || "").trim()
  const project = fp && settings.projects?.[fp] ? settings.projects[fp] : null
  const scope = project ? "project" : "global"
  const enabled = scope === "project" ? (project?.enabled ?? settings.global?.enabled !== false) : settings.global?.enabled !== false
  const source = scope === "project"
    ? (Array.isArray(project?.rules) && project?.rules.length > 0 ? project.rules : settings.global?.rules || defaultRealityCheckRules())
    : (settings.global?.rules || defaultRealityCheckRules())
  if (!enabled) return []
  const seen = new Map<string, RealityCheckRule>()
  for (const rule of source) {
    const normalized = normalizeRule(rule)
    if (!normalized || !REALITY_CHECK_RULE_IDS.has(normalized.id)) continue
    seen.set(normalized.id, normalized)
  }
  if (seen.size === 0) {
    for (const rule of defaultRealityCheckRules()) {
      const normalized = normalizeRule(rule)
      if (normalized && REALITY_CHECK_RULE_IDS.has(normalized.id)) seen.set(normalized.id, normalized)
    }
  }
  return Array.from(seen.values())
}

export function getRealityCheckView(projectFingerprint = currentProjectFingerprint || ""): {
  scope: "global" | "project"
  project_id: string | null
  enabled: boolean
  rules: RealityCheckRule[]
} {
  const settings = readRealityCheckSettings()
  const fp = String(projectFingerprint || "").trim()
  const project = fp && settings.projects?.[fp] ? settings.projects[fp] : null
  const scope = project ? "project" : "global"
  const enabled = scope === "project" ? (project?.enabled ?? settings.global?.enabled !== false) : settings.global?.enabled !== false
  const rules = getRealityCheckRulesForProject(fp)
  return {
    scope,
    project_id: project ? fp : null,
    enabled,
    rules,
  }
}

function mergeManagedRules(baseRules: FlowRule[], managedRules: FlowRule[]): FlowRule[] {
  const base = baseRules.filter((rule) => !REALITY_CHECK_RULE_IDS.has(rule.id))
  const seen = new Set(base.map((rule) => rule.id))
  const merged = [...base]
  for (const rule of managedRules) {
    if (!rule || seen.has(rule.id)) continue
    merged.push(rule)
    seen.add(rule.id)
  }
  return merged
}

function compileFlowPattern(pattern: string): RegExp {
  const source = String(pattern || "").trim()
  if (!source) return new RegExp("$^")
  if (source.startsWith("(?i)")) {
    return new RegExp(source.slice(4), "i")
  }
  return new RegExp(source)
}

function loadRules(): FlowRule[] {
  const rulesPath = resolveRulesPath()
  try {
    const rulesMtime = existsSync(rulesPath) ? statSync(rulesPath).mtimeMs : 0
    const realityFile = getRealityCheckSettingsFile()
    const realityMtime = existsSync(realityFile) ? statSync(realityFile).mtimeMs : 0
    const scopeKey = String(currentProjectFingerprint || "")
    const cacheKey = `${rulesMtime}:${realityMtime}:${scopeKey}`
    if (_cachedRules && _realityCheckCacheKey === "__test__") return _cachedRules
    if (_cachedRules && cacheKey === _realityCheckCacheKey) return _cachedRules
    if (!existsSync(rulesPath)) {
      _cachedRules = mergeManagedRules([], getRealityCheckRulesForProject(scopeKey))
      _realityCheckCacheKey = cacheKey
      return _cachedRules
    }
    const j = safeJsonParse(readFileSync(rulesPath, "utf-8")) as { rules?: FlowRule[] }
    const baseRules = Array.isArray(j.rules) ? j.rules.map(normalizeRule).filter(Boolean) as FlowRule[] : []
    _cachedRules = mergeManagedRules(baseRules, getRealityCheckRulesForProject(scopeKey))
    _rulesMtime = rulesMtime
    _realityCheckCacheKey = cacheKey
    return _cachedRules
  } catch {
    _cachedRules = []
    return _cachedRules
  }
}

function recordFlowWarn(hit: RecordFlowWarnInput): void {
  try {
    let state: any = {}
    const stateFile = getStateFile()
    if (existsSync(stateFile)) {
      try { state = safeJsonParse(readFileSync(stateFile, "utf-8")) } catch {}
    } else {
      mkdirSync(dirname(stateFile), { recursive: true })
    }
    state.flow_warns ??= []
    const dedupKey = `${hit.id}|${hit.filePath}`
    const anyExisting = state.flow_warns.some((w: any) => {
      const wKey = `${w.rule_id}|${w.filePath}`
      return wKey === dedupKey
    })
    if (!anyExisting) {
      state.flow_warns.push({
        at: new Date().toISOString(),
        sid: process.pid || "?",
        rule_id: hit.id,
        severity: hit.severity,
        filePath: hit.filePath,
        description: hit.description,
      })
    }
    if (state.flow_warns.length > 200) {
      state.flow_warns = state.flow_warns.slice(-200)
    }
    const fp = { flow_warns: state.flow_warns }
    if (_stateWriter) _stateWriter(fp)
    else {
      const stateFile = getStateFile()
      const existing = safeJsonParse(existsSync(stateFile) ? readFileSync(stateFile, "utf-8") : "{}")
      const merged = Object.assign({}, existing, fp)
      const tmpFile = stateFile + ".tmp." + Date.now()
      writeFileSync(tmpFile, JSON.stringify(merged, null, 2))
      renameSync(tmpFile, stateFile)
    }
  } catch {}
}

export function checkFlowRules({ tool, filePath, content }: CheckFlowRulesInput): FlowHit[] {
  const rules = loadRules()
  const hits: FlowHit[] = []
  const toolName = String(tool || "").trim().toLowerCase()

  for (const rule of rules) {
    const triggerName = String(rule.trigger || "").trim().toLowerCase()
    if (triggerName !== toolName) continue
    const target = toolName === "write" ? (filePath || "") : (content || filePath || "")
    let re: RegExp
    try { re = compileFlowPattern(rule.pattern) } catch { continue }
    if (!re.test(target)) continue

    const key = `${rule.id}::${filePath || ""}`
    if (_flowWarnsSeen.has(key)) {
      hits.push({ ...rule, filePath, deduped: true })
      continue
    }
    _flowWarnsSeen.add(key)
    persistFlowDedupKey(key)
    const hit: FlowHit = { ...rule, filePath, deduped: false }
    hits.push(hit)
    recordFlowWarn(hit)
  }

  return hits
}

export function getFlowWarns(): any[] {
  try {
    const stateFile = getStateFile()
    if (!existsSync(stateFile)) return []
    const s = safeJsonParse(readFileSync(stateFile, "utf-8"))
    return s?.flow_warns || []
  } catch { return [] }
}

export function getSessionFlowCounts(): Record<FlowSeverity, number> {
  const counts: Record<FlowSeverity, number> = { warn: 0, hint: 0, flag: 0 }
  const rules = loadRules()
  for (const key of _flowWarnsSeen) {
    const [ruleId] = key.split("::")
    const rule = rules.find((r) => r.id === ruleId)
    if (rule && counts[rule.severity] !== undefined) counts[rule.severity]++
  }
  return counts
}

export function resetForTest(rules: FlowRule[]): void {
  _cachedRules = rules
  _flowWarnsSeen.clear()
  _cachedRealityCheck = null
  _realityCheckMtime = 0
  _realityCheckCacheKey = "__test__"
  // Sync mtime so loadRules() returns test rules instead of reloading from file.
  try { _rulesMtime = statSync(resolveRulesPath()).mtimeMs } catch {}
}

export function resetAll(): void {
  _flowWarnsSeen.clear()
  _cachedRules = null
  _rulesMtime = 0
  _cachedRealityCheck = null
  _realityCheckMtime = 0
  _realityCheckCacheKey = ""
}

export function addFlowRule(rule: FlowRule): void {
  const rules = loadRules()
  rules.push(rule)
  writeFileSync(resolveRulesPath(), JSON.stringify({ rules }, null, 2), "utf-8")
  _cachedRules = rules
  _rulesMtime = statSync(resolveRulesPath()).mtimeMs
}

export function recordFlowTodo({ filePath, content }: FlowTodoInput): number {
  try {
    const flowTodoFile = getFlowTodoFile()
    mkdirSync(dirname(flowTodoFile), { recursive: true })
    const todoRe = /(?:\/\/\s*|\#\s*)(TODO|FIXME|HACK)[\s:]+(.+)$/i
    const todos: Array<{ type: string; text: string }> = []
    for (const line of content.split("\n")) {
      const m = line.match(todoRe)
      if (m) {
        todos.push({ type: m[1], text: m[2].trim() })
      }
    }
    if (todos.length === 0) return 0

    const dedupKey = `${filePath || ""}::${todos.map(t => `${t.type}:${t.text}`).join("|")}`
    const existingLines: string[] = existsSync(flowTodoFile)
      ? readFileSync(flowTodoFile, "utf-8").trim().split("\n").filter(Boolean)
      : []
    const existingKeys = new Set<string>()
    for (const line of existingLines) {
      try {
        const entry = safeJsonParse(line)
        if (entry && entry.filePath && entry.todos) {
          const key = `${entry.filePath}::${entry.todos.map((t: any) => `${t.type}:${t.text}`).join("|")}`
          existingKeys.add(key)
        }
      } catch {}
    }
    if (existingKeys.has(dedupKey)) return 0

    const entry = JSON.stringify({
      at: new Date().toISOString(),
      filePath,
      todos,
    }) + "\n"
    appendFileSync(flowTodoFile, entry)
    try {
      const lines = readFileSync(flowTodoFile, "utf-8").trim().split("\n").filter(Boolean)
      if (lines.length > MAX_FLOW_TODOS) {
        writeFileSync(flowTodoFile, lines.slice(-Math.floor(MAX_FLOW_TODOS / 2)).join("\n") + "\n")
      }
    } catch {}
    console.error(`[flow-enforcer] 📋 Extracted ${todos.length} TODO(s) from ${filePath} → .flow-todo-queue.jsonl`)
    return todos.length
  } catch { return 0 }
}

export function getFlowTodos(): Array<{ filePath: string; todos: Array<{ type: string; text: string }> }> {
  try {
    const flowTodoFile = getFlowTodoFile()
    if (!existsSync(flowTodoFile)) return []
    const raw = readFileSync(flowTodoFile, "utf-8").trim()
    if (!raw) return []
    return raw.split("\n").filter(Boolean).map(line => safeJsonParse(line)).filter(Boolean)
  } catch { return [] }
}

export function syncFlowTodosToNative(upsertFn?: (entry: { content: string; filePath: string; priority: string; source: string }) => void): number {
  const entries = getFlowTodos()
  let count = 0
  for (const entry of entries) {
    for (const todo of entry.todos || []) {
      const priority = todo.type === "FIXME" ? "high" : todo.type === "HACK" ? "medium" : "low"
      if (upsertFn) {
        upsertFn({
          content: `[${todo.type}] ${todo.text}`,
          filePath: entry.filePath || "",
          priority,
          source: "flow",
        })
      }
      count++
    }
  }
  return count
}
