// SPDX-License-Identifier: MIT
// Contract: `npx vibeostheog uninstall` leaves NO vibeOS artifact behind.
// Runs scripts/uninstall.mjs against a fully synthetic HOME so the real
// machine (crontab, launchctl, npm link) is never touched.

import { test } from "node:test"
import assert from "node:assert/strict"
import { execFileSync } from "node:child_process"
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from "node:fs"
import { join, dirname } from "node:path"
import { tmpdir } from "node:os"
import { fileURLToPath } from "node:url"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const UNINSTALL = join(ROOT, "scripts", "uninstall.mjs")

// Minimal JSONC-tolerant read, mirroring the uninstaller's own parser.
function readJsonc(path) {
  return readFileSync(path, "utf8")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "")
}

function writeFile(path, content) {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
}

function seedInstall() {
  const home = mkdtempSync(join(tmpdir(), "vibeos-uninstall-home-"))
  const project = mkdtempSync(join(tmpdir(), "vibeos-uninstall-proj-"))

  const ocHome = join(home, ".opencode")
  const xdgHome = join(home, ".config", "opencode")
  const desktopHome = join(home, "Library", "Application Support", "ai.opencode.desktop")

  const vibeConfig = {
    $schema: "https://opencode.ai/config.json",
    plugin: ["/some/path/vibeOS.js", "other-plugin"],
    agent: { vibe: {}, "vibe-cheap": {}, "vibe-medium": {}, "vibe-brain": {}, keeper: {} },
    default_agent: "vibe-brain",
  }

  for (const h of [ocHome, xdgHome, desktopHome]) {
    writeFile(join(h, "opencode.json"), JSON.stringify(vibeConfig, null, 2))
    writeFile(join(h, "plugins", "vibeOS.js"), "// bundle")
    writeFile(join(h, "plugins", ".env.production"), "VIBEOS_API_TOKEN=x")
    writeFile(join(h, "plugins", "opencode-event-retention.mjs"), "// retention")
    writeFile(join(h, "plugins", "assets", "a.txt"), "asset")
    writeFile(join(h, ".opencode", "skills", "vibe", "SKILL.md"), "---\nname: vibe\n---\n")
    writeFile(join(h, "skills", "vibe", "SKILL.md"), "---\nname: vibe\n---\n")
    // Launch-agent stdout/stderr sink (deploy.mjs points the plist here).
    writeFile(join(h, "opencode-retention.log"), "log line")
    // Pattern store (src/lib/pattern-store.ts writes these at OpenCode home root).
    writeFile(join(h, "learned-patterns.json"), "{}")
    writeFile(join(h, "recent-events.jsonl"), "{}\n")
  }

  // JSONC variant of the config also carries the registration.
  writeFile(join(xdgHome, "opencode.jsonc"), JSON.stringify(vibeConfig, null, 2))

  // Runtime state homes.
  writeFile(join(home, ".vibeos", "delegation-state.json"), "{}")
  writeFile(join(home, ".vibetheog", "model-tiers.json"), "{}")
  writeFile(join(desktopHome, "vibeOS", "blackbox-state.json"), "{}")
  writeFile(join(home, ".vibelm-debug", "x.log"), "d")

  // Legacy home-root deployment.
  writeFile(join(home, "opencode.json"), JSON.stringify(vibeConfig, null, 2))
  writeFile(join(home, "plugins", "vibeOS.js"), "// legacy bundle")

  // Project-level artifacts.
  writeFile(join(project, "opencode.json"), JSON.stringify(vibeConfig, null, 2))
  writeFile(join(project, ".opencode", "plugins", "vibeOS.js"), "// project bundle")
  writeFile(
    join(project, ".opencode", "skills", "myproj", "SKILL.md"),
    "---\nname: project-myproj\ndescription: Auto-generated by vibeOS.\n---\n",
  )
  writeFile(
    join(project, ".opencode", "skills", "handwritten", "SKILL.md"),
    "---\nname: handwritten\ndescription: written by a human\n---\n",
  )
  writeFile(join(project, "undefined", ".vibeOS-locks", ".keep"), "")

  return { home, project, ocHome, xdgHome, desktopHome }
}

function runUninstall(env) {
  return execFileSync(process.execPath, [UNINSTALL], {
    encoding: "utf8",
    cwd: env.cwd,
    env: {
      ...process.env,
      HOME: env.home,
      VIBEOS_HOME: env.vibeosHome || join(env.home, ".vibeos"),
      VIBEOS_UNINSTALL_SKIP_SYSTEM: "1",
      VIBEOS_OPENCODE_HOME: "",
      XDG_CONFIG_HOME: "",
    },
  })
}

test("uninstall removes every vibeOS artifact from every OpenCode home", () => {
  const s = seedInstall()
  try {
    runUninstall({ home: s.home, cwd: s.project })

    for (const h of [s.ocHome, s.xdgHome, s.desktopHome]) {
      for (const rel of [
        ["plugins", "vibeOS.js"],
        ["plugins", ".env.production"],
        ["plugins", "opencode-event-retention.mjs"],
        ["plugins", "assets"],
        [".opencode", "skills", "vibe"],
        ["skills", "vibe"],
        ["opencode-retention.log"],
        ["learned-patterns.json"],
        ["recent-events.jsonl"],
      ]) {
        assert.equal(existsSync(join(h, ...rel)), false, `leftover: ${join(h, ...rel)}`)
      }
    }
  } finally {
    rmSync(s.home, { recursive: true, force: true })
    rmSync(s.project, { recursive: true, force: true })
  }
})

test("uninstall strips vibe registration from opencode.json AND opencode.jsonc", () => {
  const s = seedInstall()
  try {
    runUninstall({ home: s.home, cwd: s.project })

    const paths = [
      join(s.ocHome, "opencode.json"),
      join(s.xdgHome, "opencode.json"),
      join(s.xdgHome, "opencode.jsonc"),
      join(s.desktopHome, "opencode.json"),
      join(s.home, "opencode.json"),
      join(s.project, "opencode.json"),
    ]
    for (const p of paths) {
      const raw = JSON.parse(readJsonc(p))
      assert.equal(
        JSON.stringify(raw.plugin || []).includes("vibeOS"),
        false,
        `plugin ref survived in ${p}`,
      )
      for (const name of ["vibe", "vibe-cheap", "vibe-medium", "vibe-brain"]) {
        assert.equal(Boolean(raw.agent?.[name]), false, `agent ${name} survived in ${p}`)
      }
      assert.equal(raw.default_agent, undefined, `default_agent survived in ${p}`)
      assert.equal(Boolean(raw.agent?.keeper), true, `non-vibe agent was destroyed in ${p}`)
    }
  } finally {
    rmSync(s.home, { recursive: true, force: true })
    rmSync(s.project, { recursive: true, force: true })
  }
})

test("uninstall removes runtime state homes and the stray deploy artifact", () => {
  const s = seedInstall()
  try {
    runUninstall({ home: s.home, cwd: s.project })
    assert.equal(existsSync(join(s.home, ".vibeos")), false)
    assert.equal(existsSync(join(s.home, ".vibetheog")), false)
    assert.equal(existsSync(join(s.desktopHome, "vibeOS")), false)
    assert.equal(existsSync(join(s.home, ".vibelm-debug")), false)
    assert.equal(existsSync(join(s.home, "plugins", "vibeOS.js")), false)
    assert.equal(existsSync(join(s.project, "undefined")), false)
  } finally {
    rmSync(s.home, { recursive: true, force: true })
    rmSync(s.project, { recursive: true, force: true })
  }
})

test("uninstall removes the auto-generated project skill but keeps hand-written ones", () => {
  const s = seedInstall()
  try {
    runUninstall({ home: s.home, cwd: s.project })
    assert.equal(existsSync(join(s.project, ".opencode", "skills", "myproj")), false)
    assert.equal(existsSync(join(s.project, ".opencode", "skills", "handwritten", "SKILL.md")), true)
  } finally {
    rmSync(s.home, { recursive: true, force: true })
    rmSync(s.project, { recursive: true, force: true })
  }
})

test("uninstall writes the marker and is idempotent on a second run", () => {
  const s = seedInstall()
  try {
    runUninstall({ home: s.home, cwd: s.project })
    assert.equal(existsSync(join(s.ocHome, "vibeOS-uninstalled")), true)
    assert.equal(existsSync(join(s.xdgHome, "vibeOS-uninstalled")), true)
    const second = runUninstall({ home: s.home, cwd: s.project })
    assert.match(second, /uninstall complete|Nothing to do/)
  } finally {
    rmSync(s.home, { recursive: true, force: true })
    rmSync(s.project, { recursive: true, force: true })
  }
})

test("uninstall on a bare HOME with nothing installed does not throw", () => {
  const home = mkdtempSync(join(tmpdir(), "vibeos-uninstall-bare-"))
  const project = mkdtempSync(join(tmpdir(), "vibeos-uninstall-bareproj-"))
  try {
    const out = runUninstall({ home, cwd: project })
    assert.match(out, /uninstall complete|Nothing to do/)
  } finally {
    rmSync(home, { recursive: true, force: true })
    rmSync(project, { recursive: true, force: true })
  }
})

test("the deployed plugin dir is a resolvable location for the uninstaller", () => {
  // vibe uninstall runs from <ocHome>/plugins/vibeOS.js and resolves
  // join(here, "uninstall.mjs"). deploy.mjs must put it there.
  const deploy = readFileSync(join(ROOT, "scripts", "deploy.mjs"), "utf8")
  assert.match(deploy, /dist['"], ['"]uninstall\.mjs/)
  assert.match(deploy, /pluginDir, ['"]uninstall\.mjs['"]/)

  const bundleScript = readFileSync(join(ROOT, "scripts", "build-bundle.mjs"), "utf8")
  assert.match(bundleScript, /uninstall\.mjs/)

  const trinity = readFileSync(join(ROOT, "src", "lib", "trinity-tool.ts"), "utf8")
  assert.match(trinity, /join\(here, "uninstall\.mjs"\)/)
})

test("uninstall removes the deployed copy of itself from the plugin dir", () => {
  const s = seedInstall()
  try {
    for (const h of [s.ocHome, s.xdgHome]) writeFile(join(h, "plugins", "uninstall.mjs"), "// deployed")
    runUninstall({ home: s.home, cwd: s.project })
    for (const h of [s.ocHome, s.xdgHome]) {
      assert.equal(existsSync(join(h, "plugins", "uninstall.mjs")), false)
    }
  } finally {
    rmSync(s.home, { recursive: true, force: true })
    rmSync(s.project, { recursive: true, force: true })
  }
})

// A VIBEOS_HOME pointing at a directory vibeOS does not own must NEVER be
// deleted wholesale. ~/.claude was vibeOS's own default VIBEOS_HOME before
// commit b14861c9, and that commit dropped the guard that excluded it — so an
// uninstall would recursively delete Claude Code's home: projects/, memory/,
// session history, settings.
test("uninstall refuses to delete a VIBEOS_HOME pointing at a foreign home dir", () => {
  const home = mkdtempSync(join(tmpdir(), "vibeos-foreign-home-"))
  const project = mkdtempSync(join(tmpdir(), "vibeos-foreign-proj-"))
  try {
    const claudeHome = join(home, ".claude")
    writeFile(join(claudeHome, "projects", "p", "session.jsonl"), "{}\n")
    writeFile(join(claudeHome, "projects", "p", "memory", "MEMORY.md"), "- [n](n.md)\n")
    writeFile(join(claudeHome, "settings.json"), "{}")

    runUninstall({ home, cwd: project, vibeosHome: claudeHome })

    assert.equal(existsSync(join(claudeHome, "settings.json")), true, "~/.claude/settings.json was destroyed")
    assert.equal(existsSync(join(claudeHome, "projects", "p", "session.jsonl")), true, "session history was destroyed")
    assert.equal(existsSync(join(claudeHome, "projects", "p", "memory", "MEMORY.md")), true, "memory was destroyed")
  } finally {
    rmSync(home, { recursive: true, force: true })
    rmSync(project, { recursive: true, force: true })
  }
})

test("uninstall refuses a VIBEOS_HOME of / or the home dir itself", () => {
  for (const bad of ["/", "HOME_ITSELF"]) {
    const home = mkdtempSync(join(tmpdir(), "vibeos-badroot-"))
    const project = mkdtempSync(join(tmpdir(), "vibeos-badroot-proj-"))
    try {
      writeFile(join(home, "keepme.txt"), "do not delete")
      runUninstall({ home, cwd: project, vibeosHome: bad === "HOME_ITSELF" ? home : bad })
      assert.equal(existsSync(join(home, "keepme.txt")), true, `VIBEOS_HOME=${bad} wiped the home dir`)
    } finally {
      rmSync(home, { recursive: true, force: true })
      rmSync(project, { recursive: true, force: true })
    }
  }
})
